### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by dpashkevich** [ignacio/LuaNode-Socket.IO#2]
Hi!
Thanks for creating LuaNode and LuaNode-Socket.IO!

This issue is kind of meta. I'd just like to know if LuaNode-Socket.IO is usable in production at the moment and do you have any plans on continuing its development?

**Comment by ignacio** [comment]
Hi!

I'm using it in production but I had to sacrifice all transports but XHR polling and Multipart. Websockets won't work since the protocol has changed and I didn't update the code.

The performance is good. At least for my needs (a web based chat system) and the browsers I need to support.

I would like to update to Socket.IO 1.0 after it is released (since this version was based on 0.7pre), but it would take time, and that's a scarce resource right now.

So... it is usable in production, but expect a bumpy road ahead :)

**Comment by dpashkevich** [comment]
Thanks for replying. I totally forgot that the websocket spec was different at the time of 0.7. 
Sounds funny that websocket abstraction library appears to not support the websocket transport itself :)

Right now I'm looking for an implementation of websockets + fallback transports for Lua and there doesn't seem to be many options so I may end up contributing to your project if I jump on the LuaNode train :)
